"""Tests for honest captured-observation calibration reports."""

from argparse import Namespace
from datetime import datetime, timedelta, timezone

import pytest
from pydantic import ValidationError

from app.evaluation.calibration import (
    CalibrationManifest,
    DatasetClass,
    ReviewStatus,
    build_calibration_report,
    file_sha256,
    load_calibration_dataset,
)
from app.schemas.observation import (
    ObservationProvenance,
    ObservationSourceType,
    TrackObservation,
)
from scripts.export_live_rf_calibration import write_dataset


START = datetime(2026, 8, 3, 12, 0, tzinfo=timezone.utc)
LATITUDE_PER_SECOND = 300 / 3600 / 60


def observation(
    seconds: int,
    *,
    longitude: float = 0,
    source_type: ObservationSourceType = ObservationSourceType.SIMULATION,
    source_id: str = "calibration-smoke",
    receiver_id: str | None = None,
) -> TrackObservation:
    timestamp = START + timedelta(seconds=seconds)
    return TrackObservation(
        provenance=ObservationProvenance(
            source_type=source_type,
            source_id=source_id,
            receiver_id=receiver_id,
        ),
        icao_hex="A1B2C3",
        observed_at=timestamp,
        received_at=timestamp + timedelta(milliseconds=100),
        latitude=seconds * LATITUDE_PER_SECOND,
        longitude=longitude,
        altitude_ft=10_000,
        ground_speed_knots=300,
        track_degrees=0,
    )


def manifest_for(
    observations: tuple[TrackObservation, ...],
    *,
    observations_sha256: str = "0" * 64,
) -> CalibrationManifest:
    return CalibrationManifest(
        dataset_id="generated-calibration-smoke",
        dataset_class=DatasetClass.GENERATED_CONTROL,
        review_status=ReviewStatus.UNREVIEWED,
        source_type=ObservationSourceType.SIMULATION,
        source_id="calibration-smoke",
        license_id="CC0-1.0",
        attribution="Generated by the test suite",
        captured_from=min(item.observed_at for item in observations),
        captured_to=max(item.observed_at for item in observations),
        observation_count=len(observations),
        observations_sha256=observations_sha256,
    )


def test_generated_clean_control_is_not_eligible_for_field_claims() -> None:
    observations = tuple(observation(index) for index in range(12))

    report = build_calibration_report(manifest_for(observations), observations)

    assert report["claim_scope"] == "engineering_validation_only"
    assert report["routine_alert_rate_eligible"] is False
    assert report["coverage"]["observed_track_hours"] == round(11 / 3600, 6)
    assert report["pair_evidence"]["status_counts"]["FLAGGED"] == 0
    assert report["window_evidence"]["status_counts"]["FLAGGED"] == 0
    assert report["alert_episodes"]["count"] == 0


def test_repeated_gradual_drift_flags_are_grouped_into_one_episode() -> None:
    observations = tuple(
        observation(index, longitude=index * 0.00002) for index in range(12)
    )

    report = build_calibration_report(manifest_for(observations), observations)

    assert report["pair_evidence"]["status_counts"]["FLAGGED"] == 0
    assert report["window_evidence"]["status_counts"]["FLAGGED"] == 7
    assert report["alert_episodes"]["count"] == 1
    episode = report["alert_episodes"]["items"][0]
    assert episode["evaluation_count"] == 7
    assert episode["evidence_types"] == ["WINDOW"]
    assert episode["rules"] == ["CUMULATIVE_POSITION_RESIDUAL"]


def test_observed_track_hours_exclude_long_unobserved_gaps() -> None:
    observations = tuple(observation(index) for index in (0, 1, 100, 101))

    report = build_calibration_report(manifest_for(observations), observations)

    assert report["coverage"]["observed_track_hours"] == round(2 / 3600, 6)


def test_captured_rf_manifest_requires_live_receiver_and_manual_review() -> None:
    with pytest.raises(ValidationError, match="LIVE_RF"):
        CalibrationManifest(
            dataset_id="invalid-capture",
            dataset_class=DatasetClass.CAPTURED_RF,
            review_status=ReviewStatus.UNREVIEWED,
            source_type=ObservationSourceType.SIMULATION,
            source_id="source",
            license_id="PRIVATE-LOCAL",
            attribution="Local receiver owner",
            captured_from=START,
            captured_to=START,
            observation_count=1,
            observations_sha256="0" * 64,
        )

    reviewed = CalibrationManifest(
        dataset_id="reviewed-capture",
        dataset_class=DatasetClass.CAPTURED_RF,
        review_status=ReviewStatus.ROUTINE_TRAFFIC_REVIEWED,
        source_type=ObservationSourceType.LIVE_RF,
        source_id="home-sdr",
        receiver_id="receiver-1",
        license_id="PRIVATE-LOCAL",
        attribution="Local receiver owner",
        captured_from=START,
        captured_to=START,
        observation_count=1,
        observations_sha256="0" * 64,
    )

    assert reviewed.routine_alert_rate_eligible is True


def test_loader_verifies_hash_count_and_observation_contract(tmp_path) -> None:
    observations = tuple(observation(index) for index in range(6))
    observations_path = tmp_path / "observations.jsonl"
    observations_path.write_text(
        "".join(item.model_dump_json() + "\n" for item in observations),
        encoding="utf-8",
    )
    manifest = manifest_for(
        observations,
        observations_sha256=file_sha256(observations_path),
    )
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(manifest.model_dump_json(indent=2), encoding="utf-8")

    loaded_manifest, loaded_observations = load_calibration_dataset(
        manifest_path, observations_path
    )

    assert loaded_manifest == manifest
    assert loaded_observations == observations

    observations_path.write_text("{}\n", encoding="utf-8")
    with pytest.raises(ValueError, match="sha256"):
        load_calibration_dataset(manifest_path, observations_path)


def export_arguments(output_directory) -> Namespace:
    return Namespace(
        output_directory=output_directory,
        dataset_id="local-rf-calibration",
        source_id="home-sdr",
        receiver_id="receiver-1",
        license_id="PRIVATE-LOCAL",
        attribution="Local receiver owner",
    )


def test_export_writes_hashed_unreviewed_live_rf_dataset(tmp_path) -> None:
    observations = tuple(
        observation(
            index,
            source_type=ObservationSourceType.LIVE_RF,
            source_id="home-sdr",
            receiver_id="receiver-1",
        )
        for index in range(6)
    )

    manifest_path, observations_path, count = write_dataset(
        observations, export_arguments(tmp_path)
    )
    manifest, loaded = load_calibration_dataset(manifest_path, observations_path)

    assert count == 6
    assert loaded == observations
    assert manifest.dataset_class is DatasetClass.CAPTURED_RF
    assert manifest.review_status is ReviewStatus.UNREVIEWED
    assert manifest.routine_alert_rate_eligible is False


def test_export_rejects_mixed_provenance_without_partial_files(tmp_path) -> None:
    observations = (
        observation(
            0,
            source_type=ObservationSourceType.LIVE_RF,
            source_id="home-sdr",
            receiver_id="receiver-1",
        ),
        observation(1),
    )

    with pytest.raises(ValueError, match="requested LIVE_RF source"):
        write_dataset(observations, export_arguments(tmp_path))

    assert list(tmp_path.iterdir()) == []
